version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  MODULES_DIR: "{{ .PROJECT_DIR }}/modules"

includes:
  terraform: .taskfiles/terraform
  github: .taskfiles/github
  
tasks:
  default:
    silent: true
    cmds: ["task -l"]
