---
name: Run Terraform CI
description: Run taskfiles associated with Terraform CI

inputs:
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: '1.6.6'
  terraform_docs_version:
    description: 'The version of Terraform Docs to use'
    required: true
    default: 'v0.18.0'
  tflint_version:
    description: 'The version of TFLint to use'
    required: true
    default: 'v0.47.0'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Task
      uses: illbjorn/setup-taskfile@main

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - uses: lablabs/setup-terraform-docs@v1
      name: Setup Terraform docs
      with:
        terraform_docs_version: ${{ inputs.terraform_docs_version }}

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: ${{ inputs.tflint_version }}

    - name: Check Terraform
      shell: bash
      run: task terraform:check
