version: "3"

tasks:
  
  #zsh-autocompletion:
  #  desc: https://terraform-docs.io/user-guide/installation/#zsh
  #  cmds:
  #    - terraform-docs completion zsh > /usr/local/share/zsh/site-functions/_terraform-docs
  #    - autoload -U compinit && compinit
  all:
    desc: Runs all terraform tasks.
    cmds:
      - task: fmt
      - task: lint
      - task: docs

  fmt:
    desc: Formats terraform configuration files.
    cmds:
      - terraform fmt -recursive

  lint:
    desc: Lints terraform configuration files.
    cmds:
      - tflint
  
  docs:
    desc: Generates docs for all terraform modules.
    cmds: 
      - find {{ .MODULES_DIR }} -type d -maxdepth 1 -mindepth 1 -exec sh -c 'cd "{}" && terraform-docs markdown . > README.md' \;
