version: "3"

tasks:

  check:
    desc: Checks if the terraform configuration files are formatted and linted.
    cmds:
      - task: fmt-check
      - task: lint-check
      - task: docs-check
      - task: validate

  fix:
    desc: Fixes the formatting of the terraform configuration files.
    cmds:
      - task: fmt
      - task: lint
      - task: docs

  lint:
    desc: Lints the terraform configuration files.
    cmds:
      - tflint --recursive --fix

  lint-check:
    desc: Checks if the terraform configuration files are linted.
    cmds:
      - tflint --recursive

  fmt:
    desc: Formats the terraform configuration files.
    cmds:
      - terraform fmt -recursive

  fmt-check:
    desc: Checks if the terraform configuration files are formatted.
    cmds:
      - terraform fmt -recursive -check
  
  docs-check:
    desc: Checks if the terraform configuration files are documented.
    cmds:
      - find {{ .MODULES_DIR }} -type d -maxdepth 1 -mindepth 1 -exec sh -c 'cd "{}" && terraform-docs markdown --output-file README.md --output-check .' \;

  docs:
    desc: Generates docs for all terraform modules.
    cmds: 
      - find {{ .MODULES_DIR }} -type d -maxdepth 1 -mindepth 1 -exec sh -c 'cd "{}" && terraform-docs markdown --output-file README.md .' \;

  validate:
    desc: Validates the terraform configuration files.
    cmds:
      - find {{ .MODULES_DIR }} -type d -maxdepth 1 -mindepth 1  -exec sh -c 'cd "{}" && terraform init --backend=false && terraform validate' \;
