# Terraform
brew "tgenv"
brew "tfenv"
brew "tflint"
brew "terraform-docs"

# Pipeline Testing
brew "act"

# Go and Terratest dependencies
brew "go"
brew "git"
brew "sshpass"

# CNI
brew "cilium-cli"

# Kubernetes
tap "fluxcd/tap"
brew "helm"
brew "helmfile"

# Task
tap "go-task/tap"

# Talos
tap "siderolabs/tap"
brew "siderolabs/tap/talosctl"

# Misc
brew "yq"
brew "jq"