---
name: Pull Request CI Checks

on:
  pull_request:
    branches:
      - main

env:
  terraform_version: '1.6.6'
  terraform_docs_version: 'v0.18.0'
  tflint_version: 'v0.47.0'

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform CI
        uses: ./.github/actions/terraform-ci
        with:
          terraform_version: ${{ env.terraform_version }}
          terraform_docs_version: ${{ env.terraform_docs_version }}
          tflint_version: ${{ env.tflint_version }}